# ============ 用户相关 ============
ACCOUNT_STATUS_NORMAL = 0
ACCOUNT_STATUS_BANNED = 1
ACCOUNT_STATUS_CANCELLED = 2

GENDER_MALE = "MALE"
GENDER_FEMALE = "FEMALE"
GENDER_UNKNOWN = "UNKNOWN"

GENDER_CHOICES = [
    (GENDER_MALE, "男"),
    (GENDER_FEMALE, "女"),
    (GENDER_UNKNOWN, "未知"),
]

PRIVACY_PUBLIC = 0
PRIVACY_FRIENDS = 1
PRIVACY_PRIVATE = 2

# ============ 笔记相关 ============
NOTE_TYPE_IMAGE = 0
NOTE_TYPE_VIDEO = 1

NOTE_STATUS_DRAFT = 0
NOTE_STATUS_PUBLISHED = 1
NOTE_STATUS_TAKEN_DOWN = 2

MAX_NOTE_IMAGES = 8
MAX_NOTE_TAGS = 8
MAX_VIDEO_DURATION = 300

# ============ 互动相关 ============
NOTIFICATION_TYPE_LIKE = "like"
NOTIFICATION_TYPE_COMMENT = "comment"
NOTIFICATION_TYPE_FOLLOW = "follow"
NOTIFICATION_TYPE_FAVORITE = "favorite"

NOTIFICATION_TYPE_CHOICES = [
    (NOTIFICATION_TYPE_LIKE, "点赞"),
    (NOTIFICATION_TYPE_COMMENT, "评论"),
    (NOTIFICATION_TYPE_FOLLOW, "关注"),
    (NOTIFICATION_TYPE_FAVORITE, "收藏"),
]

# ============ 安全相关 ============
MAX_LOGIN_FAIL_COUNT = 3
LOGIN_LOCK_MINUTES = 5
TOKEN_LIFETIME_DAYS = 7
MAX_SEARCH_HISTORY = 20
RECYCLE_BIN_DAYS = 30

# ============ 业务限制 ============
MAX_NICKNAME_LENGTH = 15
MAX_BIO_LENGTH = 500
MAX_COMMENT_LENGTH = 300
MAX_AVATAR_SIZE_MB = 5

# ============ 模型 Choice 元组 ============
NOTE_TYPE_CHOICES = [
    (NOTE_TYPE_IMAGE, "图文"),
    (NOTE_TYPE_VIDEO, "视频"),
]

NOTE_STATUS_CHOICES = [
    (NOTE_STATUS_DRAFT, "草稿"),
    (NOTE_STATUS_PUBLISHED, "已发布"),
    (NOTE_STATUS_TAKEN_DOWN, "下架"),
]

ACCOUNT_STATUS_CHOICES = [
    (ACCOUNT_STATUS_NORMAL, "正常"),
    (ACCOUNT_STATUS_BANNED, "封禁"),
    (ACCOUNT_STATUS_CANCELLED, "注销"),
]

PRIVACY_CHOICES = [
    (PRIVACY_PUBLIC, "公开"),
    (PRIVACY_FRIENDS, "仅好友"),
    (PRIVACY_PRIVATE, "私密"),
]
