# Generated by Django 4.2.30 on 2026-06-14 02:42

import apps.social.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFolder',
            fields=[
                ('id', models.CharField(default=apps.social.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('note_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_folders',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.CharField(default=apps.social.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('user', 'note')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.CharField(default=apps.social.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.CharField(default=apps.social.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='social.favoritefolder')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
                'unique_together': {('user', 'note', 'folder')},
            },
        ),
    ]
