# Generated by Django 4.2.30 on 2026-06-14 02:42

import apps.notes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(default=apps.notes.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('type', models.IntegerField(choices=[(0, '图文'), (1, '视频')], default=0)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '已发布'), (2, '下架')], default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('fav_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('taken_down_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=apps.notes.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('hot_value', models.IntegerField(default=0)),
                ('note_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.CharField(default=apps.notes.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.tag')),
            ],
            options={
                'db_table': 'note_tags',
                'unique_together': {('note', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, through='notes.NoteTag', to='notes.tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.CharField(default=apps.notes.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='notes/')),
                ('media_type', models.IntegerField(choices=[(0, '图片'), (1, '视频')], default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_list', to='notes.note')),
            ],
            options={
                'db_table': 'media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=apps.notes.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments/')),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.note')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
