# Generated by Django 4.2.30 on 2026-06-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
