# Generated by Django 4.2.30 on 2026-06-21 09:06

import apps.notes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.IntegerField(choices=[(0, 'image'), (1, 'video')], default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'published'), (2, 'taken_down')], default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.IntegerField(choices=[(0, 'image'), (1, 'video')], default=0),
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.CharField(default=apps.notes.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'view_history',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'note')},
            },
        ),
    ]
