# Generated by Django 4.2.30 on 2026-06-21 13:30

import apps.search.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearchTerm',
            fields=[
                ('id', models.CharField(default=apps.search.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hot_search_terms',
                'ordering': ['-search_count'],
            },
        ),
    ]
